(() => {
'use strict';
const D=window.YH_DATA, TAU=Math.PI*2, $=s=>document.querySelector(s);
const screens={home:$('#home'),chapters:$('#chapters'),levels:$('#levels'),game:$('#gameScreen')};
const canvas=$('#game'),ctx=canvas.getContext('2d');
let chapterIndex=0,levelIndex=0,rings=[],clasps=[],drag=null,selected=null,moves=0,sound=true,audio=null,toastTimer=0;
const save=JSON.parse(localStorage.getItem('yuhuan-qiaojie-save')||'{"completed":[],"unlocked":1}');

function show(name){Object.values(screens).forEach(s=>s.classList.remove('active'));screens[name].classList.add('active')}
function makeChapters(){const grid=$('#chapterGrid');grid.innerHTML='';D.chapters.forEach((c,i)=>{const el=document.createElement('button');el.className='chapter-card';el.style.setProperty('--c1',c.bg[0]);el.style.setProperty('--c2',c.bg[1]);el.style.setProperty('--gem',c.gem[1]);el.style.setProperty('--glow',c.glow);el.innerHTML=`<span class="gem"></span><h3>${c.name}</h3><p>${c.sub}</p>`;el.onclick=()=>openLevels(i);grid.appendChild(el)})}
function openLevels(ci){chapterIndex=ci;$('#levelsEyebrow').textContent=D.chapters[ci].name;const grid=$('#levelGrid');grid.innerHTML='';for(let i=0;i<11;i++){const open=i===0||i<save.unlocked,b=document.createElement('button');b.className='level-card'+(open?'':' locked');b.innerHTML=`<strong>${i+1}</strong><span>${i<5?(open?'可游玩':'未解锁'):'待制作'}</span>`;b.onclick=()=>{if(i<5&&open)start(ci,i);else toast(i>=5?'此关卡留给你继续编辑':'先完成前一关')};grid.appendChild(b)}show('levels')}
function start(ci,li){chapterIndex=ci;levelIndex=li;$('#chapterName').textContent=D.chapters[ci].name;$('#levelName').textContent=D.levels[li].name;show('game');reset()}
function reset(){moves=0;$('#moves').textContent=0;drag=selected=null;$('#complete').classList.remove('show');const L=D.levels[levelIndex];rings=L.rings.map((r,i)=>({...r,rotation:r.gap,alpha:1,scale:1,removed:false,removing:false,z:r.z??i}));clasps=L.clasps.map(c=>({...c,released:false,fade:1}));draw()}

$('#continueBtn').onclick=()=>start(0,0);$('#chapterBtn').onclick=()=>show('chapters');$('#chaptersBack').onclick=()=>show('home');$('#levelsBack').onclick=()=>show('chapters');$('#gameBack').onclick=()=>show('levels');$('#chooseBtn').onclick=()=>openLevels(chapterIndex);$('#resetBtn').onclick=reset;$('#replayBtn').onclick=reset;$('#nextBtn').onclick=()=>start(chapterIndex,Math.min(levelIndex+1,4));$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'音':'静'};$('#hintBtn').onclick=()=>{const r=nextPlayableRing();if(!r)return toast('当前没有可脱开的玉环');const c=activeFor(r)[0];toast(`先转 ${r.id} 环，让缺口越过发亮的金扣`)};

const norm=a=>{while(a>Math.PI)a-=TAU;while(a<-Math.PI)a+=TAU;return a};
const angleDistance=(a,b)=>Math.abs(norm(a-b));
const ring=id=>rings.find(r=>r.id===id);
const prereqMet=c=>!c.after||c.after.every(id=>ring(id)?.removed);
const visibleClasp=c=>!c.released&&ring(c.a)&&ring(c.b)&&!ring(c.a).removed&&!ring(c.b).removed;
const activeClasp=c=>visibleClasp(c)&&prereqMet(c);
const activeFor=r=>clasps.filter(c=>activeClasp(c)&&c.unlock===r.id);
function nextPlayableRing(){return rings.filter(r=>!r.removed&&!r.removing&&activeFor(r).length).sort((a,b)=>activeFor(a).length-activeFor(b).length||b.z-a.z)[0]}
function claspGeometry(c){const a=ring(c.a),b=ring(c.b),base=Math.atan2(b.y-a.y,b.x-a.x)+(c.offset||0),pa={x:a.x+Math.cos(base)*a.r,y:a.y+Math.sin(base)*a.r},pb={x:b.x-Math.cos(base)*b.r,y:b.y-Math.sin(base)*b.r};return{x:(pa.x+pb.x)/2,y:(pa.y+pb.y)/2,rot:base,angleA:Math.atan2(pa.y-a.y,pa.x-a.x),angleB:Math.atan2(pb.y-b.y,pb.x-b.x)}}
function targetAngle(c,r){const g=claspGeometry(c);return c.a===r.id?g.angleA:g.angleB}
function pointerPos(e){const b=canvas.getBoundingClientRect();return{x:(e.clientX-b.left)*canvas.width/b.width,y:(e.clientY-b.top)*canvas.height/b.height}}
function hitRing(r,p){const d=Math.hypot(p.x-r.x,p.y-r.y);if(d<r.r-32||d>r.r+32)return false;const a=Math.atan2(p.y-r.y,p.x-r.x);return angleDistance(a,r.rotation)>.48}
canvas.addEventListener('pointerdown',e=>{ensureAudio();const p=pointerPos(e);selected=[...rings].filter(r=>!r.removed&&!r.removing).sort((a,b)=>b.z-a.z).find(r=>hitRing(r,p));if(!selected)return;canvas.setPointerCapture(e.pointerId);const a=Math.atan2(p.y-selected.y,p.x-selected.x);drag={id:e.pointerId,last:a,total:0,prev:selected.rotation,releasedThisGesture:false};selected.z=100;draw()});
canvas.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id||!selected)return;const p=pointerPos(e),a=Math.atan2(p.y-selected.y,p.x-selected.x),delta=norm(a-drag.last);if(Math.abs(delta)>.5)return;drag.prev=selected.rotation;selected.rotation=norm(selected.rotation+delta);drag.total+=Math.abs(delta);drag.last=a;checkRelease(selected,drag.prev,selected.rotation);draw()});
function endDrag(e){if(!drag||e.pointerId!==drag.id)return;if(drag.total>.08){moves++;$('#moves').textContent=moves;jadeTap(.32)}drag=selected=null;normalizeZ();draw()}
canvas.addEventListener('pointerup',endDrag);canvas.addEventListener('pointercancel',endDrag);
function crossed(prev,now,target){const d1=norm(target-prev),d2=norm(now-prev);return d2>=0?d1>=0&&d1<=d2:d1<=0&&d1>=d2}
function checkRelease(r,prev,now){if(drag.releasedThisGesture||drag.total<.28)return;for(const c of activeFor(r)){const t=targetAngle(c,r);const aligned=angleDistance(now,t)<.12;const approached=angleDistance(prev,t)<.34||crossed(prev,now,t);if(aligned&&approached){drag.releasedThisGesture=true;releaseClasp(c,r);break}}}
function releaseClasp(c,r){c.released=true;jadeRelease();toast(`脱开一扣 · ${Math.max(0,activeFor(r).length)} 扣未解`);animateClasp(c);setTimeout(()=>{if(activeFor(r).length===0&&!r.removing)removeRing(r)},280)}
function animateClasp(c){const t0=performance.now();function step(t){const k=Math.min(1,(t-t0)/310);c.fade=1-k;draw();if(k<1)requestAnimationFrame(step)}requestAnimationFrame(step)}
function normalizeZ(){rings.filter(r=>!r.removed).sort((a,b)=>a.z-b.z).forEach((r,i)=>r.z=i)}
function removeRing(r){r.removing=true;const t0=performance.now();function step(t){const k=Math.min(1,(t-t0)/620),e=1-Math.pow(1-k,3);r.alpha=1-e;r.scale=1+.06*e;draw();if(k<1)requestAnimationFrame(step);else{r.removed=true;r.removing=false;draw();if(rings.every(x=>x.removed))complete()}}requestAnimationFrame(step)}
function complete(){jadeWin();const g=chapterIndex*11+levelIndex;save.completed=[...new Set([...save.completed,g])];save.unlocked=Math.max(save.unlocked,levelIndex+2);localStorage.setItem('yuhuan-qiaojie-save',JSON.stringify(save));$('#completeText').textContent=`共转动 ${moves} 次`;setTimeout(()=>$('#complete').classList.add('show'),250)}

function draw(){const C=D.chapters[chapterIndex];ctx.clearRect(0,0,900,1100);drawBackground(C);drawTray(C);drawParticles(C);rings.filter(r=>!r.removed).sort((a,b)=>a.z-b.z).forEach(r=>drawRing(r,C));clasps.filter(visibleClasp).forEach(c=>drawClasp(c,C));if(selected)drawSelection(selected)}
function drawBackground(C){const g=ctx.createLinearGradient(0,0,0,1100);g.addColorStop(0,C.bg[0]);g.addColorStop(.55,C.bg[1]);g.addColorStop(1,'#2b1c2b');ctx.fillStyle=g;ctx.fillRect(0,0,900,1100);ctx.save();ctx.globalAlpha=.28;for(let i=0;i<5;i++){ctx.fillStyle=i%2?'#fff2f7':'#ffd5e3';ctx.beginPath();ctx.arc(90+i*185,120+(i%2)*46,35+i*5,0,TAU);ctx.fill()}ctx.restore()}
function drawTray(C){ctx.save();ctx.shadowColor='rgba(41,17,34,.48)';ctx.shadowBlur=34;ctx.shadowOffsetY=22;const g=ctx.createRadialGradient(450,520,80,450,540,460);g.addColorStop(0,'rgba(255,251,250,.96)');g.addColorStop(.64,'rgba(255,225,234,.93)');g.addColorStop(.9,'rgba(239,187,207,.9)');g.addColorStop(1,'rgba(164,105,128,.92)');ctx.fillStyle=g;roundRect(70,95,760,890,85);ctx.fill();ctx.lineWidth=8;ctx.strokeStyle='rgba(230,194,123,.72)';ctx.stroke();ctx.shadowColor='transparent';ctx.lineWidth=2;ctx.strokeStyle='rgba(255,255,255,.6)';roundRect(92,117,716,846,72);ctx.stroke();ctx.restore()}
function drawParticles(C){ctx.save();ctx.globalAlpha=.32;for(let i=0;i<24;i++){const x=(i*163)%900,y=110+((i*257)%850),r=1+(i%4);ctx.fillStyle=i%3===0?'#fff':C.gem[0];ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fill()}ctx.restore()}
function ringArc(r){return{start:r.rotation+.5,end:r.rotation+TAU-.5}}
function drawRing(r,C){const {start,end}=ringArc(r),lw=38;ctx.save();ctx.globalAlpha=r.alpha;ctx.translate(r.x,r.y);ctx.scale(r.scale,r.scale);ctx.translate(-r.x,-r.y);ctx.lineCap='round';ctx.shadowColor='rgba(90,38,67,.28)';ctx.shadowBlur=18;ctx.shadowOffsetY=10;ctx.beginPath();ctx.arc(r.x,r.y,r.r,start,end);ctx.strokeStyle='rgba(74,46,68,.32)';ctx.lineWidth=lw+8;ctx.stroke();ctx.shadowColor='transparent';const g=ctx.createLinearGradient(r.x-r.r,r.y-r.r,r.x+r.r,r.y+r.r);g.addColorStop(0,'rgba(255,255,255,.92)');g.addColorStop(.12,C.gem[0]);g.addColorStop(.33,C.gem[1]);g.addColorStop(.52,'rgba(255,255,255,.72)');g.addColorStop(.76,C.gem[1]);g.addColorStop(1,C.gem[2]);ctx.globalAlpha=r.alpha*.76;ctx.beginPath();ctx.arc(r.x,r.y,r.r,start,end);ctx.strokeStyle=g;ctx.lineWidth=lw;ctx.stroke();ctx.globalAlpha=r.alpha*.32;ctx.strokeStyle='#fff';ctx.lineWidth=8;ctx.beginPath();ctx.arc(r.x-3,r.y-5,r.r-2,start+.06,end-.06);ctx.stroke();ctx.globalAlpha=r.alpha*.18;ctx.strokeStyle=C.gem[2];ctx.lineWidth=7;ctx.setLineDash([7,28,16,36]);ctx.beginPath();ctx.arc(r.x+3,r.y+4,r.r-4,start+.1,end-.1);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=r.alpha;drawEnd(r,start,C,lw);drawEnd(r,end,C,lw);ctx.restore()}
function drawEnd(r,a,C,lw){const x=r.x+Math.cos(a)*r.r,y=r.y+Math.sin(a)*r.r;ctx.save();ctx.translate(x,y);ctx.rotate(a+Math.PI/2);const g=ctx.createRadialGradient(-5,-5,2,0,0,lw*.48);g.addColorStop(0,'#fff');g.addColorStop(.28,C.gem[0]);g.addColorStop(.76,C.gem[1]);g.addColorStop(1,C.gem[2]);ctx.fillStyle=g;ctx.strokeStyle='rgba(92,51,79,.42)';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,0,lw*.4,lw*.32,0,0,TAU);ctx.fill();ctx.stroke();ctx.restore()}
function drawClasp(c,C){const g=claspGeometry(c),active=activeClasp(c);ctx.save();ctx.globalAlpha=c.fade??1;ctx.translate(g.x,g.y);ctx.rotate(g.rot);ctx.shadowColor=active?'rgba(255,211,112,.7)':'rgba(70,39,21,.32)';ctx.shadowBlur=active?15:7;ctx.shadowOffsetY=5;roundRect(-31,-19,62,38,12);ctx.fillStyle='#6d4216';ctx.fill();ctx.shadowColor='transparent';const gold=ctx.createLinearGradient(-30,-14,30,14);gold.addColorStop(0,'#7d4d17');gold.addColorStop(.17,'#d89b33');gold.addColorStop(.38,'#fff1a7');gold.addColorStop(.55,'#c78424');gold.addColorStop(.78,'#ffe692');gold.addColorStop(1,'#75420f');roundRect(-30,-14,60,28,10);ctx.fillStyle=gold;ctx.fill();ctx.lineWidth=2;ctx.strokeStyle='#7f4c11';ctx.stroke();ctx.strokeStyle='rgba(255,250,194,.8)';ctx.beginPath();ctx.moveTo(-19,-7);ctx.lineTo(19,-7);ctx.stroke();if(c.diamond){ctx.beginPath();ctx.arc(0,0,6,0,TAU);ctx.fillStyle='#f9fdff';ctx.fill();ctx.strokeStyle='#a67b25';ctx.lineWidth=2;ctx.stroke()}if(!active){ctx.fillStyle='rgba(74,47,54,.28)';roundRect(-30,-14,60,28,10);ctx.fill()}ctx.restore()}
function drawSelection(r){ctx.save();ctx.strokeStyle='rgba(255,224,159,.9)';ctx.lineWidth=3;ctx.setLineDash([9,11]);ctx.beginPath();ctx.arc(r.x,r.y,r.r+31,0,TAU);ctx.stroke();ctx.restore()}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1350)}
function ensureAudio(){if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume()}
function tone(freq,when,dur,gain){if(!sound)return;ensureAudio();const o=audio.createOscillator(),g=audio.createGain(),f=audio.createBiquadFilter();o.type='sine';o.frequency.value=freq;f.type='bandpass';f.frequency.value=freq;f.Q.value=9;g.gain.setValueAtTime(gain,when);g.gain.exponentialRampToValueAtTime(.00001,when+dur);o.connect(f).connect(g).connect(audio.destination);o.start(when);o.stop(when+dur)}
function jadeTap(p=1){if(!sound)return;ensureAudio();const t=audio.currentTime;[1220,2410,3520].forEach((f,i)=>tone(f,t+i*.004,.13+i*.04,.032*p/(i+1)))}
function jadeRelease(){if(!sound)return;ensureAudio();const t=audio.currentTime;[1430,2160,2890,3810].forEach((f,i)=>tone(f,t+i*.04,.5,.055/(i+1)))}
function jadeWin(){if(!sound)return;ensureAudio();const t=audio.currentTime;[1047,1319,1568,2093].forEach((f,i)=>tone(f,t+i*.12,.7,.06/(1+i*.3)))}
makeChapters();draw();
})();
