(()=>{'use strict';
const DATA=window.YH_DATA,TAU=Math.PI*2,$=s=>document.querySelector(s),gallery=$('#gallery'),gameScreen=$('#gameScreen'),levelScreen=$('#levelScreen'),grid=$('#chapterGrid'),levelGrid=$('#levelGrid'),canvas=$('#game'),ctx=canvas.getContext('2d');
let chapterIndex=0,levelIndex=0,rings=[],clasps=[],moves=0,drag=null,selected=null,sound=true,audio=null,toastTimer=0;
const progress=JSON.parse(localStorage.getItem('yh-progress')||'{"unlocked":1,"completed":[]}');
DATA.chapters.forEach((c,i)=>{const el=document.createElement('article');el.className='chapter-card';el.style.setProperty('--b1',c.bg[0]);el.style.setProperty('--b2',c.bg[1]);el.style.setProperty('--jade',c.jade[1]);el.innerHTML=`<h3>${c.name}</h3><p>${c.quote}</p><span class="badge">首关免费试玩</span>`;el.onclick=()=>start(i,0);grid.appendChild(el)});
function buildLevelGrid(){levelGrid.innerHTML='';for(let i=0;i<88;i++){const ch=Math.floor(i/11),li=i%11,open=li===0||i<progress.unlocked,b=document.createElement('button');b.className='level-card'+(open?'':' locked');b.innerHTML=`<strong>${i+1}</strong><span>${li===0?'免费试玩':open?'已解锁':'🔒'}</span>`;b.onclick=()=>open?start(ch,Math.min(li,4)):toast('此玉结尚未解锁');levelGrid.appendChild(b)}}
function show(s){[gallery,gameScreen,levelScreen].forEach(x=>x.classList.remove('active'));s.classList.add('active')}
function start(ci,li){chapterIndex=ci;levelIndex=li;show(gameScreen);$('#chapterName').textContent=DATA.chapters[ci].name;$('#levelName').textContent=DATA.levels[li].name;$('#quote').textContent=DATA.chapters[ci].quote;reset()}
function reset(){moves=0;$('#moves').textContent='0';drag=selected=null;$('#complete').classList.remove('show');const L=DATA.levels[levelIndex];rings=L.rings.map((r,i)=>({...r,rotation:r.gap,removed:false,removing:false,alpha:1,scale:1,z:r.z??i}));clasps=L.clasps.map(c=>({...c,released:false,fade:1}));draw()}
$('#backBtn').onclick=()=>show(gallery);$('#levelsBtn').onclick=()=>{buildLevelGrid();show(levelScreen)};$('#levelBackBtn').onclick=()=>show(gameScreen);$('#resetBtn').onclick=reset;$('#replayBtn').onclick=reset;$('#nextBtn').onclick=()=>start(chapterIndex,Math.min(levelIndex+1,4));$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'音':'静'};$('#hintBtn').onclick=()=>{const r=nextRing();if(!r)return;const c=activeFor(r)[0];toast(c?`先转「${r.id}」环：将缺口准确对准金扣。`:'此环已完全脱扣')};
const norm=a=>{while(a>Math.PI)a-=TAU;while(a<-Math.PI)a+=TAU;return a},ad=(a,b)=>Math.abs(norm(a-b));
function ring(id){return rings.find(r=>r.id===id)}
function claspReady(c){return !c.released&&(!c.after||c.after.every(id=>ring(id)?.removed))&&ring(c.a)&&ring(c.b)&&!ring(c.a).removed&&!ring(c.b).removed}
function activeFor(r){return clasps.filter(c=>claspReady(c)&&c.unlock===r.id)}
function nextRing(){return rings.filter(r=>!r.removed&&!r.removing&&activeFor(r).length).sort((a,b)=>activeFor(a).length-activeFor(b).length||b.z-a.z)[0]}
function claspGeom(c){const a=ring(c.a),b=ring(c.b),ang=Math.atan2(b.y-a.y,b.x-a.x)+(c.offset||0),pa={x:a.x+Math.cos(ang)*a.r,y:a.y+Math.sin(ang)*a.r},pb={x:b.x-Math.cos(ang)*b.r,y:b.y-Math.sin(ang)*b.r};return{x:(pa.x+pb.x)/2,y:(pa.y+pb.y)/2,rot:ang,angleA:Math.atan2(pa.y-a.y,pa.x-a.x),angleB:Math.atan2(pb.y-b.y,pb.x-b.x)}}
function contactAngle(c,r){const g=claspGeom(c);return c.a===r.id?g.angleA:g.angleB}
function pos(e){const b=canvas.getBoundingClientRect();return{x:(e.clientX-b.left)*canvas.width/b.width,y:(e.clientY-b.top)*canvas.height/b.height}}
function hit(r,p){const d=Math.hypot(p.x-r.x,p.y-r.y);if(d<r.r-34||d>r.r+34)return false;const a=Math.atan2(p.y-r.y,p.x-r.x);return ad(a,r.rotation)>.42}
canvas.onpointerdown=e=>{ensureAudio();const p=pos(e);selected=[...rings].filter(r=>!r.removed&&!r.removing).sort((a,b)=>b.z-a.z).find(r=>hit(r,p));if(!selected)return;canvas.setPointerCapture(e.pointerId);const a=Math.atan2(p.y-selected.y,p.x-selected.x);drag={id:e.pointerId,last:a,total:0,start:selected.rotation,prev:selected.rotation,releasedThisGesture:false};selected.z=100;draw()};
canvas.onpointermove=e=>{if(!drag||e.pointerId!==drag.id||!selected)return;const p=pos(e),a=Math.atan2(p.y-selected.y,p.x-selected.x),delta=norm(a-drag.last);if(Math.abs(delta)>.42)return;drag.prev=selected.rotation;selected.rotation=norm(selected.rotation+delta);drag.total+=Math.abs(delta);drag.last=a;checkCrossing(selected,drag.prev,selected.rotation);draw()};
canvas.onpointerup=canvas.onpointercancel=e=>{if(!drag||e.pointerId!==drag.id)return;if(drag.total>.08){moves++;$('#moves').textContent=moves;jadeTap(.32)}drag=selected=null;normalizeZ();draw()};
function crossed(prev,now,target){const d1=norm(target-prev),d2=norm(now-prev);return d2>=0?d1>=0&&d1<=d2:d1<=0&&d1>=d2}
function checkCrossing(r,prev,now){if(drag.releasedThisGesture||drag.total<.34)return;const list=activeFor(r);for(const c of list){const ta=contactAngle(c,r),near=ad(now,ta)<.115;if(near&&crossed(prev,now,ta)){drag.releasedThisGesture=true;releaseClasp(c,r);break}}}
function releaseClasp(c,r){c.released=true;jadeTap(.9);toast(`脱开一扣 · 还余 ${Math.max(0,activeFor(r).length)} 扣`);animateClasp(c);setTimeout(()=>{if(activeFor(r).length===0&&!r.removing)removeRing(r)},230)}
function animateClasp(c){const t0=performance.now();function step(t){const k=Math.min(1,(t-t0)/260);c.fade=1-k;draw();if(k<1)requestAnimationFrame(step)}requestAnimationFrame(step)}
function normalizeZ(){rings.filter(r=>!r.removed).sort((a,b)=>a.z-b.z).forEach((r,i)=>r.z=i)}
function removeRing(r){r.removing=true;jadeRelease();const t0=performance.now(),dur=560;function step(t){const k=Math.min(1,(t-t0)/dur),e=1-Math.pow(1-k,3);r.alpha=1-e;r.scale=1+.045*e;draw();if(k<1)requestAnimationFrame(step);else{r.removed=true;r.removing=false;draw();if(rings.every(x=>x.removed))complete();}}requestAnimationFrame(step)}
function complete(){jadeWin();const global=chapterIndex*11+levelIndex;progress.completed=[...new Set([...progress.completed,global])];progress.unlocked=Math.max(progress.unlocked,global+2);localStorage.setItem('yh-progress',JSON.stringify(progress));$('#completeText').textContent=`共转动 ${moves} 次，清响入怀。`;setTimeout(()=>$('#complete').classList.add('show'),300)}
function draw(){const C=DATA.chapters[chapterIndex];ctx.clearRect(0,0,900,1040);drawBg(C);drawDish(C);clasps.filter(c=>claspReady(c)).forEach(c=>drawClasp(c,true));rings.filter(r=>!r.removed).sort((a,b)=>a.z-b.z).forEach(r=>drawRing(r,C));clasps.filter(c=>claspReady(c)).forEach(c=>drawClasp(c,false));if(selected)drawSelected(selected)}
function drawBg(C){const g=ctx.createLinearGradient(0,0,0,1040);g.addColorStop(0,C.bg[0]);g.addColorStop(1,C.bg[1]);ctx.fillStyle=g;ctx.fillRect(0,0,900,1040);ctx.save();ctx.globalAlpha=.24;ctx.fillStyle='#fffaf0';ctx.beginPath();ctx.arc(715,125,72,0,TAU);ctx.fill();ctx.globalAlpha=.10;ctx.fillStyle=C.accent;ctx.beginPath();ctx.moveTo(0,390);ctx.quadraticCurveTo(150,245,300,390);ctx.quadraticCurveTo(460,240,610,390);ctx.quadraticCurveTo(760,275,900,390);ctx.lineTo(900,485);ctx.lineTo(0,485);ctx.fill();ctx.restore()}
function drawDish(C){ctx.save();const g=ctx.createRadialGradient(450,535,45,450,535,445);g.addColorStop(0,'rgba(255,250,244,.94)');g.addColorStop(.76,'rgba(246,228,219,.90)');g.addColorStop(.93,'rgba(244,209,201,.92)');g.addColorStop(1,'rgba(190,145,104,.58)');ctx.fillStyle=g;ctx.beginPath();ctx.ellipse(450,540,420,458,0,0,TAU);ctx.fill();ctx.lineWidth=7;ctx.strokeStyle='rgba(177,128,67,.42)';ctx.stroke();ctx.restore()}
function ringArc(r){return{start:r.rotation+.43,end:r.rotation+TAU-.43}}
function drawRing(r,C){const {start,end}=ringArc(r),lw=44;ctx.save();ctx.globalAlpha=r.alpha;ctx.translate(r.x,r.y);ctx.scale(r.scale,r.scale);ctx.translate(-r.x,-r.y);ctx.lineCap='round';ctx.shadowColor='rgba(29,50,41,.32)';ctx.shadowBlur=16;ctx.shadowOffsetY=9;ctx.beginPath();ctx.arc(r.x,r.y,r.r,start,end);ctx.strokeStyle='rgba(40,75,63,.38)';ctx.lineWidth=lw+8;ctx.stroke();ctx.shadowColor='transparent';const grad=ctx.createLinearGradient(r.x-r.r,r.y-r.r,r.x+r.r,r.y+r.r);grad.addColorStop(0,C.jade[2]);grad.addColorStop(.16,C.jade[0]);grad.addColorStop(.34,C.jade[1]);grad.addColorStop(.52,C.jade[0]);grad.addColorStop(.72,C.jade[1]);grad.addColorStop(1,C.jade[2]);ctx.beginPath();ctx.arc(r.x,r.y,r.r,start,end);ctx.strokeStyle=grad;ctx.lineWidth=lw;ctx.stroke();ctx.globalAlpha=r.alpha*.28;ctx.strokeStyle='#fff';ctx.lineWidth=9;ctx.beginPath();ctx.arc(r.x-4,r.y-6,r.r-3,start+.05,end-.05);ctx.stroke();ctx.globalAlpha=r.alpha*.20;ctx.strokeStyle=C.jade[2];ctx.lineWidth=6;ctx.setLineDash([10,25,18,35]);ctx.beginPath();ctx.arc(r.x+3,r.y+5,r.r-5,start+.1,end-.1);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=r.alpha;drawEnd(r,start,C,lw);drawEnd(r,end,C,lw);ctx.restore()}
function drawEnd(r,a,C,lw){const x=r.x+Math.cos(a)*r.r,y=r.y+Math.sin(a)*r.r,rot=a+Math.PI/2;ctx.save();ctx.translate(x,y);ctx.rotate(rot);const g=ctx.createLinearGradient(-lw/2,0,lw/2,0);g.addColorStop(0,C.jade[2]);g.addColorStop(.5,C.jade[0]);g.addColorStop(1,C.jade[2]);ctx.fillStyle=g;ctx.strokeStyle='rgba(40,78,65,.42)';ctx.lineWidth=2.5;ctx.beginPath();ctx.ellipse(0,0,lw*.43,lw*.34,0,0,TAU);ctx.fill();ctx.stroke();ctx.restore()}
function goldGrad(){const g=ctx.createLinearGradient(-28,-16,28,16);g.addColorStop(0,'#7d4b12');g.addColorStop(.18,'#c98922');g.addColorStop(.38,'#fff0a4');g.addColorStop(.55,'#d39a31');g.addColorStop(.77,'#ffe28a');g.addColorStop(1,'#78430c');return g}
function drawClasp(c,back){const g=claspGeom(c);ctx.save();ctx.globalAlpha=c.fade??1;ctx.translate(g.x,g.y);ctx.rotate(g.rot);if(back){ctx.shadowColor='rgba(64,38,9,.34)';ctx.shadowBlur=9;ctx.shadowOffsetY=5;roundRect(-31,-20,62,40,13);ctx.fillStyle='#6f420f';ctx.fill()}else{roundRect(-30,-15,60,30,11);ctx.fillStyle=goldGrad();ctx.fill();ctx.lineWidth=2.4;ctx.strokeStyle='#8d5713';ctx.stroke();ctx.strokeStyle='rgba(255,246,178,.85)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-20,-8);ctx.lineTo(20,-8);ctx.stroke();if(c.diamond){ctx.beginPath();ctx.arc(0,0,5.8,0,TAU);ctx.fillStyle='#fafdff';ctx.fill();ctx.strokeStyle='#a67b25';ctx.lineWidth=2;ctx.stroke()}}ctx.restore()}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function drawSelected(r){ctx.save();ctx.strokeStyle='rgba(205,164,72,.7)';ctx.lineWidth=3;ctx.setLineDash([9,10]);ctx.beginPath();ctx.arc(r.x,r.y,r.r+35,0,TAU);ctx.stroke();ctx.restore()}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1200)}
function ensureAudio(){if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume()}
function tone(freq,when,dur,gain){if(!sound)return;ensureAudio();const o=audio.createOscillator(),g=audio.createGain(),f=audio.createBiquadFilter();o.type='sine';o.frequency.setValueAtTime(freq,when);f.type='bandpass';f.frequency.value=freq;f.Q.value=8;g.gain.setValueAtTime(gain,when);g.gain.exponentialRampToValueAtTime(.00001,when+dur);o.connect(f).connect(g).connect(audio.destination);o.start(when);o.stop(when+dur)}
function jadeTap(p=1){if(!sound)return;ensureAudio();const t=audio.currentTime;[1180,2310,3490].forEach((f,i)=>tone(f,t+i*.004,.12+i*.04,.035*p/(i+1)))}function jadeRelease(){if(!sound)return;ensureAudio();const t=audio.currentTime;[1410,2115,2820,3760].forEach((f,i)=>tone(f,t+i*.045,.46,.055/(i+1)));tone(705,t,.55,.02)}function jadeWin(){if(!sound)return;ensureAudio();const t=audio.currentTime;[1047,1319,1568,2093].forEach((f,i)=>tone(f,t+i*.13,.7,.065/(1+i*.3)))}
draw();
})();
